server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashanrupasingha/cloud-project-configaration.git
          search-paths: platform,servises
        native:
          search-locations: classpath:/configurations/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
